version: '3'
services:
  db:
    build:
      context: .docker/mariadb
    restart: always
    ports:
      - "330*:3306"
    volumes:
      - ./storage/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    networks:
      container_network:
        ipv4_address: 10.10.*.3
  php:
    build:
      context: .docker/php-fpm
    restart: always
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
      - ./storage/var/:/var/www/html/var/
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: database
      PHP_IDE_CONFIG: "serverName=DockerPlatformRouletteClubs"
    networks:
      container_network:
        ipv4_address: 10.10.*.2
  nginx:
    build:
      context: .docker/nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80*:80"
    volumes:
      - ./src/public/:/var/www/html/public/
    networks:
      container_network:
        ipv4_address: 10.10.*.4
  webpack:
    build:
      context: .docker/webpack
    volumes:
    - ./src/front:/var/www/html/front
    - ./src/public/:/var/www/html/public

networks:
  container_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.*.0/24
